[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor = "CNmwVydeTHYEgvFoUNBQB5kr5CxgHP8Pnqpwead2GCi9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
